version: "3.9"

x-app: &default-app
  environment:
    LCP_BASE_URL: ""
    LSD_BASE_URL: ""
    DB_URI: ""
    AUTH_FILE: "/htpasswd"
    CERTIFICATE_PATH: "/cert.pem"
    PRIVATE_KEY: "/privkey.pem"
    LSD_NOTIFY_AUTH_USER: "adm_username"
    LSD_NOTIFY_AUTH_PASS: "adm_password"
    S3_ENDPOINTS: ""
    S3_ACCESS_ID: ""
    S3_DISABLE_SSL: ""
    S3_SECRET: ""
    S3_BUCKET: ""
    S3_REGION: ""
    S3_TOKEN: ""
    LOCALIZATION_LANGUAGES_ARRAY: "[\"en-US\"]"
    LOCALIZATION_FOLDER: "/i18n"
    LOCALIZATION_DEFAULT_LANGUAGE: "en-US"

services:
  lcpserver:
    <<: *default-app
    image: gcr.io/lcp-server-337422/github.com/readium/readium-lcp-server:latest-cd
    environment:
      HOST: "127.0.0.1"
      PORT: 8989 
    volumes:
      - "${PWD}/test/cert/cert-edrlab-test.pem:/cert.pem"
      - "${PWD}/test/cert/privkey-edrlab-test.pem:/privkey.pem"
      - "${PWD}/messages:/i18n"
      - "${PWD}/test/htpasswd:/htpasswd"
    networks:
      - dbnet
    ports:
      - 8989:8989

        # lsdserver:
        #   image: gcr.io/lcp-server-337422/github.com/readium/readium-lsd-server:latest-cd
        # frontend:
        #   image: gcr.io/lcp-server-337422/github.com/readium/readium-frontend-server:latest-cd

    db:
      image: mariadb:latest
        #    restart: always
      environment:
        MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: readium-lcp
      volumes:
        - db-data:/var/lib/mysql
      - "${PWD}/dbmodel/mysql_db_setup_frontend.sql:/docker-entrypoint-initdb.d/1.sql"
      - "${PWD}/dbmodel/mysql_db_setup_lsdserver.sql:/docker-entrypoint-initdb.d/2.sql"
      - "${PWD}/dbmodel/mysql_db_setup_lcpserver.sql:/docker-entrypoint-initdb.d/3.sql"

      adminer:
        image: adminer

          #restart: always
        ports:
          - 8081:8080
        networks:
          - webnet
      - dbnet

        minio:
          image: quay.io/minio/minio:RELEASE.2022-01-08T03-11-54Z
        command: server --console-address ":9001" /data 
        ports:
          - 8082:9000
      - 8083:9001
        environment:
          MINIO_ROOT_USER: admin
        MINIO_ROOT_PASSWORD: password
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
      retries: 3
    volumes:
      - minio-data:/data
    networks:
      - backnet
      - webnet

# https://hub.docker.com/r/dockersamples/visualizer
# doesn't works with docker-compose
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 8080:8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet


volumes:
  minio-data:
  db-data:

networks:
  backnet:
  webnet:
